const { initDB, getDB, saveDB } = require('../db');

async function seed() {
  console.log('开始初始化数据库...');
  
  // 等待数据库初始化完成
  await initDB();
  const db = getDB();
  
  // 清空现有数据
  db.run('DELETE FROM characters');
  console.log('清空现有字库数据');
  
  const characters = [
    { char: '一', pinyin: 'yī', strokes: 1, radical: '一', category: 'preschool', words: ['一个','一起'], sentence: '我有一个好朋友。' },
    { char: '二', pinyin: 'èr', strokes: 2, radical: '一', category: 'preschool', words: ['二月','第二'], sentence: '今天是星期二。' },
    { char: '三', pinyin: 'sān', strokes: 3, radical: '一', category: 'preschool', words: ['三个','三月'], sentence: '我家有三口人。' },
    { char: '四', pinyin: 'sì', strokes: 5, radical: '口', category: 'preschool', words: ['四个','四月'], sentence: '一年有四季。' },
    { char: '五', pinyin: 'wǔ', strokes: 4, radical: '二', category: 'preschool', words: ['五个','五月'], sentence: '我有五支铅笔。' },
    { char: '六', pinyin: 'liù', strokes: 4, radical: '八', category: 'preschool', words: ['六个','六月'], sentence: '六月是夏天。' },
    { char: '七', pinyin: 'qī', strokes: 2, radical: '一', category: 'preschool', words: ['七个','七月'], sentence: '七星瓢虫真好看。' },
    { char: '八', pinyin: 'bā', strokes: 2, radical: '八', category: 'preschool', words: ['八个','八角'], sentence: '有八只小鸟。' },
    { char: '九', pinyin: 'jiǔ', strokes: 2, radical: '丿', category: 'preschool', words: ['九个','九月'], sentence: '九朵花开了。' },
    { char: '十', pinyin: 'shí', strokes: 2, radical: '十', category: 'preschool', words: ['十个','十月'], sentence: '十月国庆节。' },
    { char: '人', pinyin: 'rén', strokes: 2, radical: '人', category: 'preschool', words: ['人们','大人'], sentence: '我是中国人。' },
    { char: '大', pinyin: 'dà', strokes: 3, radical: '大', category: 'preschool', words: ['大家','大小'], sentence: '我有一个大家庭。' },
    { char: '小', pinyin: 'xiǎo', strokes: 3, radical: '小', category: 'preschool', words: ['小学','小心'], sentence: '小鸟在树上唱歌。' },
    { char: '上', pinyin: 'shàng', strokes: 3, radical: '一', category: 'preschool', words: ['上学','上面'], sentence: '今天上学很开心。' },
    { char: '下', pinyin: 'xià', strokes: 3, radical: '一', category: 'preschool', words: ['下雨','下面'], sentence: '下雨了，要带伞。' },
    { char: '天', pinyin: 'tiān', strokes: 4, radical: '大', category: 'preschool', words: ['天空','天气'], sentence: '今天天气真好。' },
    { char: '地', pinyin: 'dì', strokes: 6, radical: '土', category: 'preschool', words: ['大地','地方'], sentence: '地上有很多花。' },
    { char: '太', pinyin: 'tài', strokes: 4, radical: '大', category: 'preschool', words: ['太阳','太大'], sentence: '太阳从东方升起。' },
    { char: '月', pinyin: 'yuè', strokes: 4, radical: '月', category: 'preschool', words: ['月亮','月光'], sentence: '月亮弯弯像小船。' },
    { char: '日', pinyin: 'rì', strokes: 4, radical: '日', category: 'preschool', words: ['日出','日子'], sentence: '日出真美丽。' },
    { char: '水', pinyin: 'shuǐ', strokes: 4, radical: '水', category: 'preschool', words: ['水果','河水'], sentence: '我爱吃水果。' },
    { char: '火', pinyin: 'huǒ', strokes: 4, radical: '火', category: 'preschool', words: ['火车','大火'], sentence: '火车跑得快。' },
    { char: '山', pinyin: 'shān', strokes: 3, radical: '山', category: 'preschool', words: ['山上','山水'], sentence: '山上有很多树。' },
    { char: '石', pinyin: 'shí', strokes: 5, radical: '石', category: 'preschool', words: ['石头','石子'], sentence: '路边有小石头。' },
    { char: '木', pinyin: 'mù', strokes: 4, radical: '木', category: 'preschool', words: ['木头','树木'], sentence: '树木很高大。' },
    { char: '花', pinyin: 'huā', strokes: 7, radical: '艹', category: 'preschool', words: ['花园','花朵'], sentence: '花园里有很多花。' },
    { char: '草', pinyin: 'cǎo', strokes: 9, radical: '艹', category: 'preschool', words: ['草地','小草'], sentence: '小草绿绿的。' },
    { char: '鸟', pinyin: 'niǎo', strokes: 5, radical: '鸟', category: 'preschool', words: ['小鸟','飞鸟'], sentence: '小鸟在天上飞。' },
    { char: '鱼', pinyin: 'yú', strokes: 8, radical: '鱼', category: 'preschool', words: ['小鱼','金鱼'], sentence: '小鱼在水里游。' },
    { char: '马', pinyin: 'mǎ', strokes: 3, radical: '马', category: 'preschool', words: ['小马','马上'], sentence: '小马跑得快。' },
    { char: '牛', pinyin: 'niú', strokes: 4, radical: '牛', category: 'preschool', words: ['水牛','牛奶'], sentence: '牛奶很有营养。' },
    { char: '羊', pinyin: 'yáng', strokes: 6, radical: '羊', category: 'preschool', words: ['小羊','羊毛'], sentence: '小羊在吃草。' },
    { char: '虫', pinyin: 'chóng', strokes: 6, radical: '虫', category: 'preschool', words: ['小虫','毛虫'], sentence: '小虫在爬行。' },
    { char: '云', pinyin: 'yún', strokes: 4, radical: '二', category: 'preschool', words: ['白云','云朵'], sentence: '天上飘着白云。' },
    { char: '雨', pinyin: 'yǔ', strokes: 8, radical: '雨', category: 'preschool', words: ['下雨','雨水'], sentence: '雨停了，彩虹出来了。' },
    { char: '风', pinyin: 'fēng', strokes: 4, radical: '风', category: 'preschool', words: ['大风','风车'], sentence: '风吹动了树叶。' },
    { char: '门', pinyin: 'mén', strokes: 3, radical: '门', category: 'preschool', words: ['大门','开门'], sentence: '请打开门。' },
    { char: '口', pinyin: 'kǒu', strokes: 3, radical: '口', category: 'preschool', words: ['门口','人口'], sentence: '门口有一棵树。' },
    { char: '手', pinyin: 'shǒu', strokes: 4, radical: '手', category: 'preschool', words: ['小手','手心'], sentence: '我们要勤洗手。' },
    { char: '足', pinyin: 'zú', strokes: 7, radical: '足', category: 'preschool', words: ['足球','手足'], sentence: '哥哥爱踢足球。' },
    { char: '耳', pinyin: 'ěr', strokes: 6, radical: '耳', category: 'preschool', words: ['耳朵','木耳'], sentence: '兔子的耳朵很长。' },
    { char: '目', pinyin: 'mù', strokes: 5, radical: '目', category: 'preschool', words: ['目光','目前'], sentence: '我们要保护好眼睛。' },
    { char: '心', pinyin: 'xīn', strokes: 4, radical: '心', category: 'preschool', words: ['开心','心中'], sentence: '我今天很开心。' },
    { char: '头', pinyin: 'tóu', strokes: 5, radical: '大', category: 'preschool', words: ['石头','头发'], sentence: '我梳好了头发。' },
    { char: '白', pinyin: 'bái', strokes: 5, radical: '白', category: 'preschool', words: ['白色','白云'], sentence: '白白的云朵像棉花。' },
    { char: '红', pinyin: 'hóng', strokes: 6, radical: '纟', category: 'preschool', words: ['红色','红花'], sentence: '五星红旗是红色的。' },
    { char: '来', pinyin: 'lái', strokes: 7, radical: '来', category: 'preschool', words: ['出来','回来'], sentence: '春天来了。' },
    { char: '去', pinyin: 'qù', strokes: 5, radical: '厶', category: 'preschool', words: ['出去','回去'], sentence: '我要去学校。' },
    { char: '走', pinyin: 'zǒu', strokes: 7, radical: '走', category: 'preschool', words: ['走路','行走'], sentence: '我们一起走路去。' },
    { char: '飞', pinyin: 'fēi', strokes: 3, radical: '飞', category: 'preschool', words: ['飞鸟','飞机'], sentence: '飞机飞得高。' },
    { char: '开', pinyin: 'kāi', strokes: 4, radical: '廾', category: 'preschool', words: ['开门','开心'], sentence: '早上开门去上学。' },
    { char: '关', pinyin: 'guān', strokes: 6, radical: '丷', category: 'preschool', words: ['关心','关门'], sentence: '请随手关门。' },
    { char: '多', pinyin: 'duō', strokes: 6, radical: '夕', category: 'preschool', words: ['多少','很多'], sentence: '草地上有很多花。' },
    { char: '少', pinyin: 'shǎo', strokes: 4, radical: '小', category: 'preschool', words: ['多少','少年'], sentence: '小朋友要少吃糖。' },
    { char: '中', pinyin: 'zhōng', strokes: 4, radical: '丨', category: 'preschool', words: ['中国','中间'], sentence: '我爱中国。' },
    { char: '国', pinyin: 'guó', strokes: 8, radical: '口', category: 'preschool', words: ['中国','国家'], sentence: '我们的国家真大。' },
    { char: '好', pinyin: 'hǎo', strokes: 6, radical: '女', category: 'preschool', words: ['好人','好看'], sentence: '你真好。' },
    { char: '春', pinyin: 'chūn', strokes: 9, radical: '日', category: 'grade1_up', words: ['春天','春风'], sentence: '春天来了，花儿开了。' },
    { char: '夏', pinyin: 'xià', strokes: 10, radical: '夂', category: 'grade1_up', words: ['夏天','夏季'], sentence: '夏天可以游泳。' },
    { char: '秋', pinyin: 'qiū', strokes: 9, radical: '禾', category: 'grade1_up', words: ['秋天','秋风'], sentence: '秋天果子熟了。' },
    { char: '冬', pinyin: 'dōng', strokes: 5, radical: '夂', category: 'grade1_up', words: ['冬天','冬季'], sentence: '冬天会下雪。' },
    { char: '林', pinyin: 'lín', strokes: 8, radical: '木', category: 'grade1_up', words: ['树林','森林'], sentence: '森林里有很多树。' },
    { char: '土', pinyin: 'tǔ', strokes: 3, radical: '土', category: 'grade1_up', words: ['泥土','土地'], sentence: '种子在泥土里发芽。' },
    { char: '力', pinyin: 'lì', strokes: 2, radical: '力', category: 'grade1_up', words: ['力气','力量'], sentence: '我的力气很大。' },
    { char: '果', pinyin: 'guǒ', strokes: 8, radical: '木', category: 'grade1_up', words: ['苹果','水果'], sentence: '苹果是水果。' },
    { char: '叶', pinyin: 'yè', strokes: 5, radical: '口', category: 'grade1_up', words: ['叶子','树叶'], sentence: '秋天树叶落了。' },
    { char: '牙', pinyin: 'yá', strokes: 4, radical: '牙', category: 'grade1_up', words: ['牙齿','月牙'], sentence: '早晚要刷牙。' },
    { char: '狗', pinyin: 'gǒu', strokes: 8, radical: '犭', category: 'grade1_up', words: ['小狗','狗狗'], sentence: '小狗是我的好朋友。' },
    { char: '猫', pinyin: 'māo', strokes: 11, radical: '犭', category: 'grade1_up', words: ['小猫','猫咪'], sentence: '小猫在睡觉。' },
    { char: '兔', pinyin: 'tù', strokes: 8, radical: '⺈', category: 'grade1_up', words: ['兔子','白兔'], sentence: '白兔爱吃萝卜。' },
    { char: '鸡', pinyin: 'jī', strokes: 7, radical: '鸟', category: 'grade1_up', words: ['小鸡','公鸡'], sentence: '公鸡打鸣了。' },
    { char: '鸭', pinyin: 'yā', strokes: 10, radical: '鸟', category: 'grade1_up', words: ['小鸭','鸭子'], sentence: '小鸭子在游泳。' },
    { char: '爸', pinyin: 'bà', strokes: 8, radical: '父', category: 'grade1_up', words: ['爸爸','老爸'], sentence: '爸爸下班回家了。' },
    { char: '妈', pinyin: 'mā', strokes: 6, radical: '女', category: 'grade1_up', words: ['妈妈','爸妈'], sentence: '妈妈做的饭真好吃。' },
    { char: '哥', pinyin: 'gē', strokes: 10, radical: '口', category: 'grade1_up', words: ['哥哥','大哥'], sentence: '哥哥在写作业。' },
    { char: '姐', pinyin: 'jiě', strokes: 8, radical: '女', category: 'grade1_up', words: ['姐姐','姐妹'], sentence: '姐姐帮我梳头。' },
    { char: '弟', pinyin: 'dì', strokes: 7, radical: '弓', category: 'grade1_up', words: ['弟弟','兄弟'], sentence: '弟弟在玩玩具。' },
    { char: '妹', pinyin: 'mèi', strokes: 8, radical: '女', category: 'grade1_up', words: ['妹妹','姐妹'], sentence: '妹妹在唱歌。' },
    { char: '爷', pinyin: 'yé', strokes: 6, radical: '父', category: 'grade1_up', words: ['爷爷','老爷'], sentence: '爷爷在看书。' },
    { char: '奶', pinyin: 'nǎi', strokes: 5, radical: '女', category: 'grade1_up', words: ['奶奶','牛奶'], sentence: '奶奶在浇花。' },
    { char: '学', pinyin: 'xué', strokes: 8, radical: '子', category: 'grade1_up', words: ['学习','学校'], sentence: '我爱学习。' },
    { char: '校', pinyin: 'xiào', strokes: 10, radical: '木', category: 'grade1_up', words: ['学校','校长'], sentence: '我们的学校真大。' },
    { char: '老', pinyin: 'lǎo', strokes: 6, radical: '老', category: 'grade1_up', words: ['老师','老人'], sentence: '老师辛苦了。' },
    { char: '师', pinyin: 'shī', strokes: 6, radical: '巾', category: 'grade1_up', words: ['老师','师父'], sentence: '老师教我们写字。' },
    { char: '文', pinyin: 'wén', strokes: 4, radical: '文', category: 'grade1_up', words: ['语文','文字'], sentence: '我喜欢语文课。' },
    { char: '字', pinyin: 'zì', strokes: 6, radical: '子', category: 'grade1_up', words: ['写字','汉字'], sentence: '我学会了写汉字。' },
    { char: '书', pinyin: 'shū', strokes: 4, radical: '乛', category: 'grade1_up', words: ['书本','看书'], sentence: '我爱看书。' },
    { char: '包', pinyin: 'bāo', strokes: 5, radical: '勹', category: 'grade1_up', words: ['书包','包子'], sentence: '书包里有很多书。' },
    { char: '笔', pinyin: 'bǐ', strokes: 10, radical: '⺮', category: 'grade1_up', words: ['铅笔','毛笔'], sentence: '我有一支新铅笔。' },
    { char: '桌', pinyin: 'zhuō', strokes: 10, radical: '木', category: 'grade1_up', words: ['桌子','书桌'], sentence: '书桌上放着书。' },
    { char: '灯', pinyin: 'dēng', strokes: 6, radical: '火', category: 'grade1_up', words: ['灯光','台灯'], sentence: '台灯照亮了书本。' },
    { char: '电', pinyin: 'diàn', strokes: 5, radical: '田', category: 'grade1_up', words: ['电话','电视'], sentence: '我们看电视。' },
    { char: '话', pinyin: 'huà', strokes: 8, radical: '讠', category: 'grade1_up', words: ['说话','电话'], sentence: '妈妈在打电话。' },
    { char: '唱', pinyin: 'chàng', strokes: 11, radical: '口', category: 'grade1_up', words: ['唱歌','演唱'], sentence: '小鸟在唱歌。' },
    { char: '歌', pinyin: 'gē', strokes: 14, radical: '欠', category: 'grade1_up', words: ['唱歌','歌曲'], sentence: '我会唱这首歌。' },
    { char: '画', pinyin: 'huà', strokes: 8, radical: '田', category: 'grade1_up', words: ['画画','图画'], sentence: '我喜欢画画。' },
    { char: '笑', pinyin: 'xiào', strokes: 10, radical: '⺮', category: 'grade1_up', words: ['笑容','欢笑'], sentence: '小朋友在欢笑。' },
    { char: '跑', pinyin: 'pǎo', strokes: 12, radical: '⻊', category: 'grade1_up', words: ['跑步','奔跑'], sentence: '哥哥在跑步。' },
    { char: '跳', pinyin: 'tiào', strokes: 13, radical: '⻊', category: 'grade1_up', words: ['跳绳','跳高'], sentence: '我们在跳绳。' },
    { char: '玩', pinyin: 'wán', strokes: 8, radical: '王', category: 'grade1_up', words: ['玩耍','好玩'], sentence: '下课了，我们去玩。' },
    { char: '做', pinyin: 'zuò', strokes: 11, radical: '亻', category: 'grade1_up', words: ['做事','做作业'], sentence: '我在做作业。' },
    { char: '写', pinyin: 'xiě', strokes: 5, radical: '冖', category: 'grade1_up', words: ['写字','写作'], sentence: '我在学写字。' },
    { char: '认', pinyin: 'rèn', strokes: 4, radical: '讠', category: 'grade1_up', words: ['认识','认真'], sentence: '我认识很多字。' },
    { char: '真', pinyin: 'zhēn', strokes: 10, radical: '目', category: 'grade1_up', words: ['认真','真正'], sentence: '他学习很认真。' },
    { char: '听', pinyin: 'tīng', strokes: 7, radical: '口', category: 'grade1_up', words: ['听课','听说'], sentence: '上课要认真听讲。' },
    { char: '看', pinyin: 'kàn', strokes: 9, radical: '目', category: 'grade1_up', words: ['看见','看书'], sentence: '我看见一只小鸟。' },
    { char: '问', pinyin: 'wèn', strokes: 6, radical: '门', category: 'grade1_up', words: ['问题','请问'], sentence: '我有一个问题。' },
    { char: '回', pinyin: 'huí', strokes: 6, radical: '口', category: 'grade1_up', words: ['回家','回来'], sentence: '放学了，我回家。' },
    { char: '给', pinyin: 'gěi', strokes: 9, radical: '纟', category: 'grade1_up', words: ['给你','送给'], sentence: '我送给你一朵花。' },
    { char: '最', pinyin: 'zuì', strokes: 12, radical: '曰', category: 'grade1_up', words: ['最好','最后'], sentence: '我最好的朋友。' },
    { char: '对', pinyin: 'duì', strokes: 5, radical: '又', category: 'grade1_up', words: ['对不起','对错'], sentence: '对不起，没关系。' },
    { char: '前', pinyin: 'qián', strokes: 9, radical: '丷', category: 'grade1_up', words: ['前面','从前'], sentence: '我在前面走。' },
    { char: '后', pinyin: 'hòu', strokes: 6, radical: '厂', category: 'grade1_up', words: ['后面','后来'], sentence: '我在后面跟着。' },
    { char: '左', pinyin: 'zuǒ', strokes: 5, radical: '工', category: 'grade1_up', words: ['左右','左边'], sentence: '我的左边是同学。' },
    { char: '右', pinyin: 'yòu', strokes: 5, radical: '口', category: 'grade1_up', words: ['左右','右边'], sentence: '商店在右边。' },
    { char: '东', pinyin: 'dōng', strokes: 5, radical: '一', category: 'grade1_up', words: ['东方','东西'], sentence: '太阳从东方升起。' },
    { char: '西', pinyin: 'xī', strokes: 6, radical: '西', category: 'grade1_up', words: ['西方','西瓜'], sentence: '夏天吃西瓜。' },
    { char: '南', pinyin: 'nán', strokes: 9, radical: '十', category: 'grade1_up', words: ['南方','南瓜'], sentence: '南方的冬天很暖和。' },
    { char: '北', pinyin: 'běi', strokes: 5, radical: '匕', category: 'grade1_up', words: ['北方','北京'], sentence: '北京是我们的首都。' },
    { char: '星', pinyin: 'xīng', strokes: 9, radical: '日', category: 'grade1_up', words: ['星星','星光'], sentence: '天上有很多星星。' },
    { char: '空', pinyin: 'kōng', strokes: 8, radical: '穴', category: 'grade1_up', words: ['天空','空气'], sentence: '天空很蓝。' },
    { char: '海', pinyin: 'hǎi', strokes: 10, radical: '氵', category: 'grade1_up', words: ['大海','海水'], sentence: '大海真广阔。' },
    { char: '阳', pinyin: 'yáng', strokes: 6, radical: '阝', category: 'grade1_up', words: ['太阳','阳光'], sentence: '阳光照在身上暖洋洋的。' },
    { char: '光', pinyin: 'guāng', strokes: 6, radical: '⺌', category: 'grade1_up', words: ['阳光','灯光'], sentence: '灯光很明亮。' },
    { char: '明', pinyin: 'míng', strokes: 8, radical: '日', category: 'grade1_up', words: ['明天','明亮'], sentence: '明天是晴天。' },
    { char: '早', pinyin: 'zǎo', strokes: 6, radical: '日', category: 'grade1_up', words: ['早上','早晨'], sentence: '早上好！' },
    { char: '晚', pinyin: 'wǎn', strokes: 11, radical: '日', category: 'grade1_up', words: ['晚上','晚安'], sentence: '晚上要早点睡。' },
    { char: '今', pinyin: 'jīn', strokes: 4, radical: '人', category: 'grade1_up', words: ['今天','今年'], sentence: '今天是星期一。' },
    { char: '年', pinyin: 'nián', strokes: 6, radical: '年', category: 'grade1_up', words: ['今年','明年'], sentence: '新年快乐。' },
    { char: '快', pinyin: 'kuài', strokes: 7, radical: '忄', category: 'grade1_up', words: ['快乐','快点'], sentence: '生日快乐！' },
    { char: '乐', pinyin: 'lè', strokes: 5, radical: '丿', category: 'grade1_up', words: ['快乐','音乐'], sentence: '音乐课很有趣。' },
    { char: '高', pinyin: 'gāo', strokes: 10, radical: '高', category: 'grade1_up', words: ['高兴','很高'], sentence: '我很高兴。' },
    { char: '美', pinyin: 'měi', strokes: 9, radical: '大', category: 'grade1_up', words: ['美丽','美好'], sentence: '花园真美丽。' },
    { char: '爱', pinyin: 'ài', strokes: 10, radical: '爫', category: 'grade1_up', words: ['爱心','爱好'], sentence: '我爱我的家。' },
    { char: '家', pinyin: 'jiā', strokes: 10, radical: '宀', category: 'grade1_up', words: ['回家','家人'], sentence: '我有一个幸福的家。' },
    { char: '饭', pinyin: 'fàn', strokes: 7, radical: '饣', category: 'grade1_up', words: ['吃饭','米饭'], sentence: '该吃饭了。' },
    { char: '菜', pinyin: 'cài', strokes: 11, radical: '艹', category: 'grade1_up', words: ['蔬菜','白菜'], sentence: '多吃蔬菜身体好。' },
    { char: '瓜', pinyin: 'guā', strokes: 5, radical: '瓜', category: 'grade1_up', words: ['西瓜','瓜子'], sentence: '西瓜很甜。' },
    { char: '雪', pinyin: 'xuě', strokes: 11, radical: '雨', category: 'grade1_down', words: ['下雪','雪人'], sentence: '冬天下雪了。' },
    { char: '百', pinyin: 'bǎi', strokes: 6, radical: '白', category: 'grade1_down', words: ['百花','一百'], sentence: '春天百花齐放。' },
    { char: '齐', pinyin: 'qí', strokes: 6, radical: '齐', category: 'grade1_down', words: ['整齐','齐心'], sentence: '大家排整齐。' },
    { char: '说', pinyin: 'shuō', strokes: 9, radical: '讠', category: 'grade1_down', words: ['说话','说明'], sentence: '说话要有礼貌。' },
    { char: '吹', pinyin: 'chuī', strokes: 7, radical: '口', category: 'grade1_down', words: ['吹风','吹气'], sentence: '春风轻轻地吹。' },
    { char: '到', pinyin: 'dào', strokes: 8, radical: '刂', category: 'grade1_down', words: ['来到','到达'], sentence: '春天来到了。' },
    { char: '处', pinyin: 'chù', strokes: 5, radical: '夂', category: 'grade1_down', words: ['到处','处处'], sentence: '到处是鲜花。' },
    { char: '动', pinyin: 'dòng', strokes: 6, radical: '力', category: 'grade1_down', words: ['动物','运动'], sentence: '我喜欢小动物。' },
    { char: '万', pinyin: 'wàn', strokes: 3, radical: '一', category: 'grade1_down', words: ['万物','一万'], sentence: '万物复苏了。' },
    { char: '冰', pinyin: 'bīng', strokes: 6, radical: '冫', category: 'grade1_down', words: ['冰雪','冰棒'], sentence: '冰雪融化了。' },
    { char: '柳', pinyin: 'liǔ', strokes: 9, radical: '木', category: 'grade1_down', words: ['柳树','柳条'], sentence: '柳树发芽了。' },
    { char: '芽', pinyin: 'yá', strokes: 7, radical: '艹', category: 'grade1_down', words: ['发芽','豆芽'], sentence: '种子发芽了。' },
    { char: '桃', pinyin: 'táo', strokes: 10, radical: '木', category: 'grade1_down', words: ['桃花','桃子'], sentence: '桃树开花了。' },
    { char: '争', pinyin: 'zhēng', strokes: 6, radical: '⺈', category: 'grade1_down', words: ['争气','争取'], sentence: '百花争艳。' },
    { char: '旗', pinyin: 'qí', strokes: 14, radical: '方', category: 'grade1_down', words: ['国旗','红旗'], sentence: '国旗在空中飘扬。' },
    { char: '城', pinyin: 'chéng', strokes: 9, radical: '土', category: 'grade1_down', words: ['城市','长城'], sentence: '长城很长。' },
    { char: '长', pinyin: 'cháng', strokes: 4, radical: '长', category: 'grade1_down', words: ['长城','长大'], sentence: '长城很长很长。' },
    { char: '路', pinyin: 'lù', strokes: 13, radical: '⻊', category: 'grade1_down', words: ['马路','路上'], sentence: '过马路要小心。' },
    { char: '故', pinyin: 'gù', strokes: 9, radical: '攵', category: 'grade1_down', words: ['故事','故乡'], sentence: '妈妈讲故事。' },
    { char: '事', pinyin: 'shì', strokes: 8, radical: '亅', category: 'grade1_down', words: ['故事','事情'], sentence: '我有一件好事。' },
    { char: '许', pinyin: 'xǔ', strokes: 6, radical: '讠', category: 'grade1_down', words: ['许多','也许'], sentence: '公园里有许多人。' },
    { char: '想', pinyin: 'xiǎng', strokes: 13, radical: '心', category: 'grade1_down', words: ['想念','想法'], sentence: '我想念奶奶。' },
    { char: '知', pinyin: 'zhī', strokes: 8, radical: '矢', category: 'grade1_down', words: ['知道','知识'], sentence: '我知道答案。' },
    { char: '道', pinyin: 'dào', strokes: 12, radical: '辶', category: 'grade1_down', words: ['知道','道路'], sentence: '我知道怎么走了。' },
    { char: '帮', pinyin: 'bāng', strokes: 9, radical: '巾', category: 'grade1_down', words: ['帮助','帮忙'], sentence: '我帮助同学。' },
    { char: '助', pinyin: 'zhù', strokes: 7, radical: '力', category: 'grade1_down', words: ['帮助','助力'], sentence: '谢谢你的帮助。' },
    { char: '题', pinyin: 'tí', strokes: 15, radical: '页', category: 'grade1_down', words: ['问题','题目'], sentence: '这道题我会做。' },
    { char: '步', pinyin: 'bù', strokes: 7, radical: '止', category: 'grade1_down', words: ['进步','脚步'], sentence: '我有很大进步。' },
    { char: '课', pinyin: 'kè', strokes: 10, radical: '讠', category: 'grade1_down', words: ['课文','上课'], sentence: '上课了。' },
    { char: '考', pinyin: 'kǎo', strokes: 6, radical: '耂', category: 'grade1_down', words: ['考试','思考'], sentence: '期末考试到了。' },
    { char: '如', pinyin: 'rú', strokes: 6, radical: '女', category: 'grade1_down', words: ['如果','如此'], sentence: '如果努力就会进步。' },
    { char: '棒', pinyin: 'bàng', strokes: 12, radical: '木', category: 'grade1_down', words: ['真棒','棒球'], sentence: '你真棒！' },
  ];

  // 使用事务批量插入字符数据
  db.run('BEGIN TRANSACTION');
  
  try {
    for (const ch of characters) {
      db.run(
        'INSERT OR IGNORE INTO characters (char, pinyin, strokes, radical, category, words, sentence) VALUES (?, ?, ?, ?, ?, ?, ?)',
        [ch.char, ch.pinyin, ch.strokes, ch.radical, ch.category, JSON.stringify(ch.words), ch.sentence]
      );
    }
    
    db.run('COMMIT');
    console.log(`种子导入完成。共导入 ${characters.length} 个汉字。`);
  } catch (error) {
    db.run('ROLLBACK');
    console.error('种子导入失败:', error);
    throw error;
  }
  
  // 保存数据库到磁盘
  saveDB();
}

// 执行种子导入
seed().catch(console.error);